---
title: "Volume Mapping"
output_dir: "docs" 
output:
  html_document:
    theme: flatly

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width=8, fig.height = 9, cache = TRUE)

library(leaflet)
library(htmltools)
library(htmlwidgets)
library(tidyverse)
library(sf)
library(rmapshaper)
library(rpgcolorsr)
library(classInt)
library(leafpop)
library(leafsync)
```


```{r add polylineoffset functions}

#Code adapted from https://gist.github.com/timelyportfolio/8f6c8cc27597466351ad377e6774c30f AND https://gist.github.com/jcheng5/c084a59717f18e947a17955007dc5f92

# This tells htmlwidgets about our plugin name, version, and
# where to find the script. (There's also a stylesheet argument
# if the plugin comes with CSS files.)

polylineoffsetplugin <- htmlDependency("leaflet.polylineoffset", "1.0.1",
  src = c(file="K:/Projects/WILMAPCO/Features/R/NetworkMapping/leaflet_polylineoffset_js"),  script = "leaflet.polylineoffset_arw.js")

#rmarkdown:::validate_html_dependency(polylineoffsetplugin)

  # A function that takes a plugin htmlDependency object and adds
# it to the map. This ensures that however or whenever the map
# gets rendered, the plugin will be loaded into the browser.

registerPlugin <- function(map, plugin) {
  map$dependencies <- c(map$dependencies, list(plugin))
  map
}

#javascript from https://trafficdash.nl/assets/leaflet.polylineoffset_arw.js

```


```{r make map function}

make_map <- function(sf, variable, legend_title) {

colors <-  rpg_color_pal("rpg_colors")(8)

breaks <- classIntervals(sf[[variable]], n=8, style="jenks")

#plot distribution
#graphics::plot(breaks, pal=colors)

#using jenks with leaflet adapted from here: #https://rstudio-pubs-static.s3.amazonaws.com/427207_c0a245962f244370bda11f05496e821f.html

breaks <- breaks$brks


pal <- colorBin(palette = colors, 
                domain = sf[[variable]],
                #create bins using the breaks object from earlier
                bins = breaks)


leaflet() %>% 
  addProviderTiles(providers$Esri.WorldGrayCanvas) %>% 
  registerPlugin(polylineoffsetplugin) %>% 
  addPolylines(data=sf, 
               weight=3, 
               color = ~pal(sf[[variable]]), 
               opacity=1, 
               popup = popupTable(sf),
               options=list(offset=3)) %>% 
  addPolygons(data=StudyArea_RFP, fill = FALSE, opacity = 1, color = "#8400a8", weight = 2) %>% 
  addLegend(pal = pal, values = sf[[variable]], opacity = 1, title = legend_title, position = "bottomright")
}




make_2_maps <- function(sf1, sf2, variable1, variable2, legend_title1, legend_title2) {

colors <-  rpg_color_pal("rpg_colors")(8)

breaks <- classIntervals(rbind(sf1[[variable1]],sf2[[variable2]]), n=8, style="fisher")

#plot distribution
#graphics::plot(breaks, pal=colors)

#using jenks with leaflet adapted from here: #https://rstudio-pubs-static.s3.amazonaws.com/427207_c0a245962f244370bda11f05496e821f.html

breaks <- breaks$brks


pal <- colorBin(palette = colors, 
                domain = sf1[[variable1]],
                #create bins using the breaks object from earlier
                bins = breaks)


m1 <- leaflet() %>% 
  addProviderTiles(providers$Esri.WorldGrayCanvas) %>% 
  registerPlugin(polylineoffsetplugin) %>% 
  addPolylines(data=sf1, 
               weight=3, 
               color = ~pal(sf1[[variable1]]), 
               opacity=1, 
               popup = popupTable(sf1),
               options=list(offset=3)) %>% 
  addPolygons(data=StudyArea_RFP, fill = FALSE, opacity = 1, color = "#8400a8", weight = 2) %>% 
  addLegend(pal = pal, values = sf1[[variable1]], opacity = 1, title = legend_title1, position = "bottomright")


m2 <- leaflet() %>% 
  addProviderTiles(providers$Esri.WorldGrayCanvas) %>% 
  registerPlugin(polylineoffsetplugin) %>% 
  addPolylines(data=sf2, 
               weight=3, 
               color = ~pal(sf2[[variable2]]), 
               opacity=1, 
               popup = popupTable(sf2),
               options=list(offset=3)) %>% 
  addPolygons(data=StudyArea_RFP, fill = FALSE, opacity = 1, color = "#8400a8", weight = 2) %>% 
  addLegend(pal = pal, values = sf2[[variable2]], opacity = 1, title = legend_title2, position = "bottomright")

return(sync(m1, m2))

}

```


```{r read in data and create map}

#st_layers("K:/Projects/WILMAPCO/Features/Transp/ChurchmanCrossing_GisInv_Delivery.gdb")

StudyArea_RFP <- st_read("K:/Projects/WILMAPCO/Features/Transp/ChurchmanCrossing_GisInv_Delivery.gdb", "StudyArea_RFP", quiet = TRUE) %>% 
  st_transform(4326) %>% 
  ms_simplify()

buffered_study_area <- st_read("K:/Projects/WILMAPCO/Features/Model/SE/Zones_2050.shp", quiet = TRUE) %>% 
  filter(RFP_bound == 1) %>%
  st_transform(2283) %>% 
  st_buffer(10560)

network_links_19 <- st_read("K:/Projects/WILMAPCO/Features/Model/networks/2019_Loaded_Link.shp", quiet = TRUE) %>% 
  st_transform(2283) %>% 
  st_filter(buffered_study_area, .predicate = st_intersects)
  
network_links_19 <- network_links_19 %>% 
  st_transform(4326) %>% 
  ms_simplify()

network_links_50 <- st_read("K:/Projects/WILMAPCO/Features/Model/networks/2050_Loaded_Link.shp", quiet = TRUE) %>% 
  st_transform(2283) %>% 
  st_filter(buffered_study_area, .predicate = st_intersects)
  
network_links_50 <- network_links_50 %>% 
  st_transform(4326) %>% 
  ms_simplify()

```

## Directional Volume 24hr (2019 and 2050)

```{r plot directional 24hr}

network_links_19_24hr_vol <- network_links_19 %>%  
  select(A, B, DISTANCE, RT_TYPE, DIR_LANE, TOT_LANE, DIR_V, DIRV_AM, DIRV_PM) %>% 
  arrange(DIR_V)


network_links_50_24hr_vol <- network_links_50 %>%  
  select(A, B, DISTANCE, RT_TYPE, DIR_LANE, TOT_LANE, DIR_V, DIRV_AM, DIRV_PM) %>% 
  arrange(DIR_V)


make_2_maps(network_links_19_24hr_vol, network_links_50_24hr_vol, "DIR_V", "DIR_V", "Dir. Vol. 24hr 2019", "Dir. Vol. 24hr 2050")

```

## Directional Volume AM (2019 and 2050)


```{r plot directional am}

make_2_maps(network_links_19_24hr_vol, network_links_50_24hr_vol, "DIRV_AM", "DIRV_AM", "Dir. Vol. AM 2019", "Dir. Vol. AM 2050")

```

## Directional Volume PM (2019 and 2050)

```{r plot directional pm}
make_2_maps(network_links_19_24hr_vol, network_links_50_24hr_vol, "DIRV_PM", "DIRV_PM", "Dir. Vol. PM 2050", "Dir. Vol. PM 2050")

```

