---
title: "WILMAPCO Model Network Analysis"
output_dir: "docs" 
output:
  html_document:
    theme: flatly

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, fig.width=12)

library(leaflet)
library(htmltools)
library(htmlwidgets)
library(tidyverse)
library(sf)
library(rmapshaper)
library(rpgcolorsr)
library(classInt)
library(leafpop)
```


```{r add polylineoffset functions}

#Code adapted from https://gist.github.com/timelyportfolio/8f6c8cc27597466351ad377e6774c30f AND https://gist.github.com/jcheng5/c084a59717f18e947a17955007dc5f92

# This tells htmlwidgets about our plugin name, version, and
# where to find the script. (There's also a stylesheet argument
# if the plugin comes with CSS files.)

polylineoffsetplugin <- htmlDependency("leaflet.polylineoffset", "1.0.1",
  src = c(file="K:/Projects/WILMAPCO/Features/R/NetworkMapping/leaflet_polylineoffset_js"),  script = "leaflet.polylineoffset_arw.js")

#rmarkdown:::validate_html_dependency(polylineoffsetplugin)

  # A function that takes a plugin htmlDependency object and adds
# it to the map. This ensures that however or whenever the map
# gets rendered, the plugin will be loaded into the browser.

registerPlugin <- function(map, plugin) {
  map$dependencies <- c(map$dependencies, list(plugin))
  map
}

src=c(file="...")

```

```{r read in data and create map}

#st_layers("K:/Projects/WILMAPCO/Features/Transp/ChurchmanCrossing_GisInv_Delivery.gdb")

StudyArea_RFP <- st_read("K:/Projects/WILMAPCO/Features/Transp/ChurchmanCrossing_GisInv_Delivery.gdb", "StudyArea_RFP", quiet = TRUE) %>% 
  st_transform(4326) %>% 
  ms_simplify()

buffered_study_area <- st_read("K:/Projects/WILMAPCO/Features/Model/SE/Zones_2050.shp", quiet = TRUE) %>% 
  filter(RFP_bound == 1) %>%
  st_transform(2283) %>% 
  st_buffer(26400)

network_links <- st_read("K:/Projects/WILMAPCO/Features/Model/networks/2019_Loaded_Link.shp", quiet = TRUE) %>% 
  st_transform(2283) %>% 
  st_filter(buffered_study_area, .predicate = st_intersects) %>% 
  select(A, B, DISTANCE, RT_TYPE, DIR_LANE, TOT_LANE, TOT_V, DIR_V, DIRV_AM, DIRV_PM, CSPDAM, CSPDPM, LINK_SP) %>% 
  arrange(DIR_V)
  
network_links <- network_links %>% 
  st_transform(4326) %>% 
  ms_simplify()

colors <-  rpg_color_pal("rpg_colors")(8)

breaks <- classIntervals(network_links$DIR_V, n=8, style="jenks")


#plot distribution
#graphics::plot(breaks, pal=colors)


breaks <- breaks$brks


pal <- colorBin(palette = colors, 
                domain = network_links$DIR_V,
                #create bins using the breaks object from earlier
                bins = breaks)


leaflet() %>% 
  addProviderTiles(providers$CartoDB.DarkMatter) %>% 
  registerPlugin(polylineoffsetplugin) %>% 
  addPolylines(data=network_links, 
               weight=3, 
               color = ~pal(DIR_V), 
               opacity=1, 
               popup = popupTable(network_links),
               options=list(offset=3)) %>% 
  addPolygons(data=StudyArea_RFP, fill = FALSE, opacity = 1, color = "#8400a8", weight = 2) %>% 
  addLegend(pal = pal, values = network_links$DIR_V, opacity = 1, title = "Directional Volume", position = "bottomright")


```


